name: Publish new release
on:
  push:
    branches:
      - main
jobs:
  Build-Bungeecord:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "8"
      - run: gradle bungeecord:jar
      - uses: actions/upload-artifact@v4
        with:
          name: commandtimer-bungeecord
          path: bungeecord/build/libs/bungeecord.jar
  Build-Velocity:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
      - run: gradle velocity:jar
      - uses: actions/upload-artifact@v4
        with:
          name: commandtimer-velocity
          path: velocity/build/libs/velocity.jar
  Release:
    needs:
      - Build-Bungeecord
      - Build-Velocity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true
      - run: echo "PLUGIN_VERSION=$(grep ^ version.yml)" >> $GITHUB_ENV
      - run: gh release create ${{ env.PLUGIN_VERSION }} -t ${{ env.PLUGIN_VERSION }} artifact/*.jar
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
